version: 2
updates:
  # Root package dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "cpb"
    assignees:
      - "cpb"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      production-dependencies:
        patterns:
          - "@anthropic-ai/*"
          - "@opentelemetry/*"
          - "d3*"
      development-dependencies:
        patterns:
          - "@types/*"
          - "@typescript-eslint/*"
          - "eslint*"
          - "jest*"
          - "typescript*"

  # Frontend package dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "cpb"
    assignees:
      - "cpb"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 2
    reviewers:
      - "cpb"
    commit-message:
      prefix: "ci"
      include: "scope"
